    const allSongs = [
        // Українські - Народні (алфавітний порядок за назвою) (last id - 20)
            { id: 'ukr-folk-1', title: "7-40", artist: "Народна", category: "Українські", subcategory: "Народні" },
            { id: 'ukr-folk-2', title: "А зорі, а зорі", artist: "Народна", category: "Українські", subcategory: "Народні" },
            { id: 'ukr-folk-3', title: "А я все дивлюся, де моя Маруся", artist: "Народна", category: "Українські", subcategory: "Народні" },
            { id: 'ukr-folk-4', title: "Дубки (Ой на горі два дубки)", artist: "Mad Heads", category: "Українські", subcategory: "Народні" },
            { id: 'ukr-folk-5', title: "За нашов стодолов", artist: "Народна", category: "Українські", subcategory: "Народні" },
            { id: 'ukr-folk-6', title: "Лілія", artist: "Народна", category: "Українські", subcategory: "Народні" },
            { id: 'ukr-folk-7', title: "Нині, нині", artist: "Народна", category: "Українські", subcategory: "Народні" },
            { id: 'ukr-folk-8', title: "Ой там у Львові", artist: "Джазова фіра", category: "Українські", subcategory: "Народні" },
            { id: 'ukr-folk-9', title: "Плакуча Гітара", artist: "Народна", category: "Українські", subcategory: "Народні" },
            { id: 'ukr-folk-10', title: "Сама п'ю, сама наливаю", artist: "Марина і компанія", category: "Українські", subcategory: "Народні" },
            { id: 'ukr-folk-11', title: "Сиджу я край віконечка", artist: "Народна", category: "Українські", subcategory: "Народні" },
            { id: 'ukr-folk-12', title: "Сині фіалки", artist: "Народна", category: "Українські", subcategory: "Народні" },
            { id: 'ukr-folk-13', title: "Смерека", artist: "Mad Heads", category: "Українські", subcategory: "Народні" },
            { id: 'ukr-folk-14', title: "Стожари", artist: "Народна", category: "Українські", subcategory: "Народні" },
            { id: 'ukr-folk-15', title: "Там, під Львівським замком", artist: "Народна", category: "Українські", subcategory: "Народні" },
            { id: 'ukr-folk-16', title: "Тернопільські каштани", artist: "Народна", category: "Українські", subcategory: "Народні" },
            { id: 'ukr-folk-17', title: "Ти ж мене підманула", artist: "Народна", category: "Українські", subcategory: "Народні" },
            { id: 'ukr-folk-18', title: "Тиха вода", artist: "Народна", category: "Українські", subcategory: "Народні" },
            { id: 'ukr-folk-19', title: "Цвіте терен", artist: "Народна", category: "Українські", subcategory: "Народні" },
            { id: 'ukr-folk-20', title: "Час рікою пливе", artist: "Народна", category: "Українські", subcategory: "Народні" },
            { id: 'ukr-folk-21', title: "Чорні очка, як терен", artist: "Народна", category: "Українські", subcategory: "Народні" },

            // Українські - Поп (last id - 145)
            { id: 'ukr-pop-1', title: "Повільно", artist: "Adam", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-2', title: "Особистий рай", artist: "Adam, Геля Зозуля", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-3', title: "Мужчина", artist: "Alena Omargalieva", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-4', title: "Твоя", artist: "Alena Omargalieva", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-5', title: "Промінь", artist: "All stars Mozgi Ent.", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-6', title: "Пірнай", artist: "Alyosha & Vlad Darwin", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-7', title: "Гарно так", artist: "Cheev", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-8', title: "Покохай мене", artist: "Chico, Qatoshi, 100лиця", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-9', title: "Все пробачати", artist: "Dan Balan, Oksana Mukha", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-10', title: "Хочеш", artist: "Dibrova, Олена Тополя", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-11', title: "Кохаю, але не зовсім", artist: "Dorofeeva", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-12', title: "Спитай у чата джипіті", artist: "Dorofeeva", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-13', title: "Смарагдове небо", artist: "Drevo", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-14', title: "Вихідний", artist: "Dzidzio", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-15', title: "Моя любов", artist: "Dzidzio", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-16', title: "Я і Сара", artist: "Dzidzio", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-17', title: "Василина", artist: "Dzidzio, Іван Попович", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-18', title: "Розлук не буде", artist: "Dzidzio, Іван Попович", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-19', title: "Киця", artist: "Dzidzio, Оля Цибульська", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-20', title: "Чекаю. Цьом", artist: "Dzidzio, Оля Цибульська", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-21', title: "Потанцюй зі мною, тату", artist: "Franko Band", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-22', title: "Охрана Отмєна", artist: "Jerry Heil", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-23', title: "Додому", artist: "Kalush", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-24', title: "Плакала", artist: "Kazka", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-25', title: "Свята", artist: "Kazka", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-26', title: "Чи разом", artist: "Kola", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-27', title: "Така спокуслива", artist: "Kozak System", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-28', title: "Люди", artist: "MamaRika, Kola", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-29', title: "Береги UA", artist: "Max Barskih", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-30', title: "Тумани UA", artist: "Max Barskih", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-31', title: "Вітрила", artist: "Melovin", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-32', title: "Кожний раз", artist: "Monatik", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-33', title: "Обіцяю", artist: "NK/Настя Каменських", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-34', title: "Почуття", artist: "NK/Настя Каменських", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-35', title: "Тримай", artist: "NK/Настя Каменських", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-36', title: "Плакала Калина", artist: "Polina Dashkova", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-37', title: "Вишиваночка", artist: "Selfy", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-38', title: "Галя балувана", artist: "Selfy", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-39', title: "Біля Тополі", artist: "Shumei", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-40', title: "Буревіями", artist: "Shumei, Zlata Ognevich", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-41', title: "Я кохана дружина", artist: "Skalnystka", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-42', title: "Любий, кохай мене", artist: "SMS", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-43', title: "Чайки", artist: "Sunguns", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-44', title: "Квітка", artist: "Tayanna", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-45', title: "Леля", artist: "Tayanna", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-46', title: "Фантастична жінка", artist: "Tayanna", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-47', title: "Шкода", artist: "Tayanna", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-48', title: "Жива", artist: "The Hardkiss", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-49', title: "Журавлі", artist: "The Hardkiss", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-50', title: "Прірва", artist: "The Hardkiss", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-51', title: "Саме ти", artist: "Vaha", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-52', title: "Гоп-Гоп-Гоп", artist: "Verka Serduchka", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-53', title: "Точка G", artist: "Vin I Vona", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-54', title: "Вишні", artist: "Wellboy", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-55', title: "Гуси", artist: "Wellboy", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-56', title: "Додому", artist: "Wellboy", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-57', title: "Погляд", artist: "Yaktak, Sobol", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-58', title: "Солодка Кара", artist: "Zlata Ognevich", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-59', title: "Танцювати", artist: "Zlata Ognevich", category: "Українські", subcategory: "Поп" },

            { id: 'ukr-pop-60', title: "Волошковий цвіт", artist: "Аліна Жук", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-61', title: "Ні я не ту кохав", artist: "Анатолій Говорадло", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-62', title: "Бред Пітт", artist: "Андріана", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-63', title: "Ой, Мамо", artist: "Андріана, Vladislav Левицький", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-119', title: "Happy end (українська версія)", artist: "Анна Добриднєва", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-64', title: "Зірочка палай", artist: "Анна Трінчер", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-65', title: "Лише тебе", artist: "Анна Трінчер", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-66', title: "Лише ти і я ", artist: "Анна Трінчер & Voloshyn", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-67', title: "Буде син", artist: "Антитіла", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-68', title: "Все красиво", artist: "Антитіла", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-69', title: "Джеральдіна", artist: "Арсен Мірзоян", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-70', title: "Дежавю", artist: "Артем Пивоваров", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-71', title: "Рандеву", artist: "Артем Пивоваров", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-72', title: "Думи", artist: "Артем Пивоваров, Dorofeeva", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-73', title: "Зорі запалали", artist: "Без Обмежень", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-74', title: "Листопад", artist: "Без Обмежень", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-75', title: "Тону", artist: "Без Обмежень", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-76', title: "Скажи мені", artist: "Бородін Максим", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-77', title: "Якби не ти", artist: "Бородін Максим", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-100', title: "Тече вода", artist: "Василь Зінкевич", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-78', title: "Гойра вісілє", artist: "Василь Мельникович", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-79', title: "Хлопці будем жити", artist: "Василь Хлистун", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-80', title: "Чорна гора", artist: "Вася Club", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-81', title: "Котику", artist: "ВІА ТоШоНаДо", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-82', title: "Весілля в Карпатах", artist: "Віктор Павлік", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-84', title: "Ні обіцянок, ні пробачень", artist: "Віктор Павлік", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-83', title: "Тарам там нема з ким", artist: "Віктор Павлік", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-85', title: "Теща (Теща, дай)", artist: "Віктор Павлік", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-86', title: "Ти подобаєшся мені", artist: "Віктор Павлік", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-87', title: "Шикидим", artist: "Віктор Павлік", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-88', title: "Я піду в далекі гори", artist: "Віктор Павлік", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-89', title: "Пінаколада", artist: "Віталій Козловський", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-90', title: "Люблю тебе", artist: "Віталій Лобач", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-139', title: "Пісня буде поміж нас", artist: "Володимир Івасюк", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-92', title: "Дим", artist: "Время и Стекло", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-93', title: "Самотня босса", artist: "Гайтана", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-94', title: "Поведи мене", artist: "Гурт Будьмо", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-95', title: "Причарувала-приворожила", artist: "Гурт Будьмо", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-96', title: "А липи цвітуть", artist: "Іво Бобул", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-97', title: "Розмова з тобою", artist: "Іво Бобул", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-98', title: "Білі троянди", artist: "Ірина Федишин", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-99', title: "Калина", artist: "Ірина Федишин", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-101', title: "Романсеро", artist: "Катерина Бужинська", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-91', title: "Ірка", artist: "Левицький", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-102', title: "Мій Син", artist: "Марина Полончак", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-103', title: "Пісня для донечки", artist: "Марина Полончак", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-104', title: "Наречена", artist: "Михайло Хома", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-105', title: "Ми будемо разом", artist: "Монте Крісто", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-106', title: "Сину, ангел мій", artist: "Надія Шестак", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-107', title: "Дівчина-весна", artist: "Наталія Бучинська", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-108', title: "Жоржини", artist: "Наталія Бучинська", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-109', title: "Карпати", artist: "Наталія Бучинська", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-110', title: "Романтично", artist: "Нікіта Кісельов", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-111', title: "Без тебе", artist: "Океан Ельзи", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-112', title: "На небі", artist: "Океан Ельзи", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-113', title: "Не йди", artist: "Океан Ельзи", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-114', title: "Вовчиця", artist: "Олег Винник", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-115', title: "Наталя-Наталі", artist: "Олег Винник", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-116', title: "Полон", artist: "Олег Винник", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-117', title: "Доню моя", artist: "Олександр Пономарьов", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-118', title: "Я ніколи нікому тебе не віддам", artist: "Олександр Пономарьов", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-120', title: "Падала зірка", artist: "Павло Доскоч", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-121', title: "Пшениця колоситься", artist: "Павло Доскоч", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-122', title: "Вона", artist: "Плач Єремії", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-124', title: "Найкращий день", artist: "Потап, Олег Винник", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-125', title: "Свят! Свят! Свят!", artist: "Потап, Олег Винник, Оля Полякова", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-123', title: "На щастя", artist: "Потап, Олег Винник, Позитив", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-126', title: "Мамо, я закохався", artist: "Роман Скорпіон", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-127', title: "Поцілую", artist: "Роман Скорпіон", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-128', title: "Фата", artist: "Роман Скорпіон", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-129', title: "Коломийка", artist: "Руслана", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-130', title: "Вона знає", artist: "Сергій Бабкін", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-131', title: "Де би я", artist: "Сергій Бабкін", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-132', title: "Пробач", artist: "Сергій Бабкін", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-133', title: "Мам", artist: "Скрябін", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-134', title: "Місця щасливих людей", artist: "Скрябін", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-135', title: "Спи собі сама", artist: "Скрябін", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-136', title: "Шампанські очі", artist: "Скрябін", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-137', title: "Мій рідний край", artist: "Софія Ротару", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-138', title: "Одна калина", artist: "Софія Ротару", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-140', title: "Червона Рута", artist: "Софія Ротару", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-141', title: "Цей сон", artist: "Степан Гіга", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-142', title: "Алкоголізм", artist: "ТІК", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-144', title: "Біла хмара, чорна хмара", artist: "ТІК", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-143', title: "Білі троянди", artist: "ТІК", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-145', title: "Не Дощ", artist: "Тіна Кароль", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-146', title: "Ніжно", artist: "Тіна Кароль", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-147', title: "Перечекати", artist: "Тіна Кароль", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-148', title: "Вільна", artist: "Тіна Кароль & Юлія Саніна", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-149', title: "Кульбаби", artist: "Тоня Матвієнко", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-150', title: "Українська лють (Bella Ciao Cover)", artist: "Христина Соловій", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-151', title: "Королєва (А баби, як баби)", artist: "Цвіт Кульбаби", category: "Українські", subcategory: "Поп" },
            { id: 'ukr-pop-152', title: "Живи", artist: "Юлія Рознен", category: "Українські", subcategory: "Поп" },


            // Українські - Рок (last id - 20)
            { id: 'ukr-rock-1', title: "Розслабся, не парся", artist: "Mad Heads", category: "Українські", subcategory: "Рок" },
            { id: 'ukr-rock-2', title: "Кораблі", artist: "The Hardkiss", category: "Українські", subcategory: "Рок" },
            { id: 'ukr-rock-3', title: "Кобра", artist: "The Hardkiss, Monatik", category: "Українські", subcategory: "Рок" },

            { id: 'ukr-rock-4', title: "Без неї ніяк", artist: "Без Обмежень", category: "Українські", subcategory: "Рок" },
            { id: 'ukr-rock-5', title: "Буду з тобою", artist: "Без Обмежень", category: "Українські", subcategory: "Рок" },
            { id: 'ukr-rock-6', title: "Було не любити", artist: "Брати Гадюкіни", category: "Українські", subcategory: "Рок" },
            { id: 'ukr-rock-7', title: "Файне місто Тернопіль", artist: "Брати Гадюкіни", category: "Українські", subcategory: "Рок" },
            { id: 'ukr-rock-8', title: "Весна", artist: "Воплі Відоплясова", category: "Українські", subcategory: "Рок" },
            { id: 'ukr-rock-9', title: "День Народження", artist: "Воплі Відоплясова", category: "Українські", subcategory: "Рок" },
            { id: 'ukr-rock-10', title: "Воїни світла UA", artist: "Ляпис Трубецкой", category: "Українські", subcategory: "Рок" },
            { id: 'ukr-rock-11', title: "Без бою", artist: "Океан Ельзи", category: "Українські", subcategory: "Рок" },
            { id: 'ukr-rock-12', title: "Зелені очі", artist: "Океан Ельзи", category: "Українські", subcategory: "Рок" },
            { id: 'ukr-rock-13', title: "Майже весна", artist: "Океан Ельзи", category: "Українські", subcategory: "Рок" },
            { id: 'ukr-rock-14', title: "Там, де нас нема", artist: "Океан Ельзи", category: "Українські", subcategory: "Рок" },
            { id: 'ukr-rock-15', title: "Люди, як кораблі", artist: "Скрябін", category: "Українські", subcategory: "Рок" },
            { id: 'ukr-rock-16', title: "Маршрутка", artist: "Скрябін", category: "Українські", subcategory: "Рок" },
            { id: 'ukr-rock-17', title: "Сам собі країна", artist: "Скрябін", category: "Українські", subcategory: "Рок" },
            { id: 'ukr-rock-18', title: "Старі фотографії", artist: "Скрябін", category: "Українські", subcategory: "Рок" },
            { id: 'ukr-rock-19', title: "Їхали козаки", artist: "Тінь Сонця", category: "Українські", subcategory: "Рок" },

            // Зарубіжні - Поп (last id - 66)
            { id: 'for-pop-1', title: "Gimme! Gimme! Gimme!", artist: "ABBA", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-2', title: "Easy On Me", artist: "Adele", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-3', title: "Hafanana", artist: "Afric Simone", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-4', title: "No Roots", artist: "Alice Merton", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-5', title: "Friends", artist: "Aura Dione", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-7', title: "Bad Guy", artist: "Billie Eilish", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-9', title: "Sorry Seems To Be The Hardest Word", artist: "Blue, Elton John", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-10', title: "Sunny", artist: "Boney M", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-11', title: "Havana", artist: "Camilla Cabello", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-12', title: "Safe And Sound", artist: "Capital Cities", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-13', title: "Sub Pielea Mea (Eroina)", artist: "Carla's Dreams", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-14', title: "Cause You Are Young", artist: "CC Catch", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-15', title: "Get Lucky", artist: "Daft Punk, Pharrell Williams", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-16', title: "Allegro Ventigo", artist: "Dan Balan", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-17', title: "Numa Numa 2", artist: "Dan Balan, Marley Waters", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-18', title: "Cake By The Ocean", artist: "DNCE", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-19', title: "Levitating Featuring DaBaby", artist: "Dua Lipa", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-20', title: "Physical", artist: "Dua Lipa", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-21', title: "Duele El Corazon", artist: "Enrique Iglesias, Wisin", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-22', title: "Worth It", artist: "Fifth Harmony, Kid Ink", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-23', title: "L.O.V.E.", artist: "Frank Sinatra", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-24', title: "Can't Take My Eyes Off You", artist: "Frankie Valli", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-25', title: "I will Survive", artist: "Gloria Gaynor", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-26', title: "Be Good", artist: "Gregory Porter", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-27', title: "I Feel Good", artist: "James Brown", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-28', title: "Let's Get Loud", artist: "Jennifer Lopez", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-29', title: "My Father's Son", artist: "Joe Cocker", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-30', title: "La Camisa Negra", artist: "Juanes", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-31', title: "Can't Stop the Feeling", artist: "Justin Timberlake", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-32', title: "Bella ciao", artist: "La Casa De Papel", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-33', title: "Shallow", artist: "Lady Gaga, Bradley Cooper", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-34', title: "Hello", artist: "Lionel Richie", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-35', title: "Despacito", artist: "Luis Fonsi, Daddy Yankee", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-36', title: "So Long", artist: "Malfa", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-37', title: "Corazon", artist: "Maluma", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-38', title: "Uptown Funk", artist: "Mark Ronson, Bruno Mars", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-39', title: "Sugar", artist: "Maroon 5", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-40', title: "This Love", artist: "Maroon 5", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-41', title: "Żono moja", artist: "Masters", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-42', title: "Feeling Good", artist: "Michael Bubble", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-43', title: "Sway", artist: "Michael Bubble", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-8', title: "Billie Jean", artist: "Michael Jackson", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-44', title: "Ai Se Eu Te Pego (Nosa Nosa)", artist: "Michel Teló", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-45', title: "Flowers", artist: "Miley Cyrus", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-46', title: "Rampampam", artist: "Minelli", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-47', title: "Cheri Cheri Lady", artist: "Modern Talking", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-48', title: "You're My Heart, You're My Soul", artist: "Modern Talking", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-49', title: "Coco Jamboo", artist: "Mr. President", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-50', title: "Be Mine", artist: "Ofenbach", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-51', title: "Happy", artist: "Pharrell Williams", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-52', title: "In The Dark", artist: "Purple Disco Machine, Sophie, the Giants", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-53', title: "Hit The Road Jack", artist: "Ray Charles", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-54', title: "Let You Love Me", artist: "Rita Ora", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-55', title: "Disko Partizani", artist: "Shantel", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-56', title: "Señorita", artist: "Shawn Mendes, Camila Cabello", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-57', title: "Venus", artist: "Shocking Blue", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-58', title: "Give Me Your Love ", artist: "Sigala", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-59', title: "Isn't She Lovely", artist: "Stevie Wonder", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-60', title: "Every Breath You Take", artist: "Sting", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-61', title: "Shape of My Heart", artist: "Sting", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-62', title: "Blinding Lights", artist: "The Weeknd", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-63', title: "Don't Be Shy", artist: "Tiesto, Karol G", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-64', title: "The Best", artist: "Tina Turner", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-65', title: "Sex Bomb", artist: "Tom Jones, Mousse T.", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-66', title: "Dance Monkey", artist: "TONES AND I", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-67', title: "Hey Nah Nah Nah", artist: "Vaya Con Dios", category: "Зарубіжні", subcategory: "Поп" },
            { id: 'for-pop-6', title: "Baila Morena", artist: "Zucchero", category: "Зарубіжні", subcategory: "Поп" },


            // Зарубіжні - Рок (last id - 16)
            { id: 'for-rock-1', title: "Highway to Hell", artist: "AC/DC", category: "Зарубіжні", subcategory: "Рок" },
            { id: 'for-rock-2', title: "Song 2", artist: "Blur", category: "Зарубіжні", subcategory: "Рок" },
            { id: 'for-rock-3', title: "It's my Life", artist: "Bon Jovi", category: "Зарубіжні", subcategory: "Рок" },
            { id: 'for-rock-4', title: "Johnny Be Goode", artist: "Chuck Berry", category: "Зарубіжні", subcategory: "Рок" },
            { id: 'for-rock-5', title: "Adventure Of A Lifetime", artist: "Coldplay", category: "Зарубіжні", subcategory: "Рок" },
            { id: 'for-rock-6', title: "Smoke On the Water", artist: "Deep Purple", category: "Зарубіжні", subcategory: "Рок" },
            { id: 'for-rock-7', title: "Jailhouse Rock", artist: "Elvis Presley", category: "Зарубіжні", subcategory: "Рок" },
            { id: 'for-rock-8', title: "Hero", artist: "Enrique Iglesias", category: "Зарубіжні", subcategory: "Рок" },
            { id: 'for-rock-9', title: "Sweet Dreams", artist: "Eurythmics, Annie Lennox, Dave Stewart", category: "Зарубіжні", subcategory: "Рок" },
            { id: 'for-rock-10', title: "I Love Rock 'n' Roll", artist: "Joan Jett, the Blackhearts", category: "Зарубіжні", subcategory: "Рок" },
            { id: 'for-rock-11', title: "Way Down We Go", artist: "KALEO", category: "Зарубіжні", subcategory: "Рок" },
            { id: 'for-rock-12', title: "Smells Like Teen Spirit", artist: "Nirvana", category: "Зарубіжні", subcategory: "Рок" },
            { id: 'for-rock-13', title: "Bohemian Rhapsody", artist: "Queen", category: "Зарубіжні", subcategory: "Рок" },
            { id: 'for-rock-14', title: "Show Must Go On", artist: "Queen", category: "Зарубіжні", subcategory: "Рок" },
            { id: 'for-rock-15', title: "Somebody Told Me", artist: "The Killers", category: "Зарубіжні", subcategory: "Рок" },
            { id: 'for-rock-16', title: "Seven Nation Army", artist: "The White Stripes", category: "Зарубіжні", subcategory: "Рок" },


            // Спеціальні - Патріотичні
            { id: 'spec-patr-1', title: "Біля Тополі", artist: "Shumei", category: "Спеціальні", subcategory: "Патріотичні" },
            { id: 'spec-patr-3', title: "Люди-Титани", artist: "Kozak System", category: "Спеціальні", subcategory: "Патріотичні" },
            { id: 'spec-patr-4', title: "Най би вже весна", artist: "Без Обмежень", category: "Спеціальні", subcategory: "Патріотичні" },
            { id: 'spec-patr-5', title: "Ой у лузі червона калина", artist: "Бумбокс", category: "Спеціальні", subcategory: "Патріотичні" },


            // Спеціальні - Новорічні
            { id: 'spec-ny-1', title: "Happy New Year", artist: "ABBA", category: "Спеціальні", subcategory: "Новорічні" },
            { id: 'spec-ny-3', title: "Jingle Bell Rock", artist: "Bobby Helms", category: "Спеціальні", subcategory: "Новорічні" },
            { id: 'spec-ny-2', title: "Jingle Bells (Rock Version)", artist: "Frank Sinatra", category: "Спеціальні", subcategory: "Новорічні" },
            { id: 'spec-ny-4', title: "Last Christmas", artist: "Wham!", category: "Спеціальні", subcategory: "Новорічні" },
            { id: 'spec-ny-5', title: "Let it Snow!", artist: "Dean Martin", category: "Спеціальні", subcategory: "Новорічні" },
    ];